services:
  qdrant:
    image: qdrant/qdrant:v1.15.1
    container_name: qdrant
    ports:
      - "6333:6333" # Dashboard: http://localhost:6333/dashboard
    volumes:
      - ./assets/qdrant_data:/qdrant/storage
  elasticsearch:
    build:
      dockerfile: elasticsearch.Dockerfile
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./assets/es_data:/usr/share/elasticsearch/data
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./assets/postgres_data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    restart: always
  jaeger:
    image: jaegertracing/all-in-one:1.72.0
    container_name: jaeger
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - LOG_LEVEL=debug
    ports:
      - "16686:16686" # to access the Jaeger UI
      - "4317:4317"
      - "4318:4318"
      - "5778:5778"
      - "9411:9411"
    depends_on:
      - elasticsearch
    restart: unless-stopped
  # FIXME: disable for now since its port conflicts with jaeger
  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib:latest
  #   container_name: otel-collector
  #   volumes:
  #     - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
  #   ports:
  #     - 1888:1888 # pprof extension
  #     - 8888:8888 # Prometheus metrics exposed by the Collector
  #     - 8889:8889 # Prometheus exporter metrics
  #     - 13133:13133 # health_check extension
  #     - 4317:4317 # OTLP gRPC receiver
  #     - 4318:4318 # OTLP http receiver
  #     - 55679:55679 # zpages extension
