services:
  qdrant:
    image: qdrant/qdrant:v1.15.1
    container_name: qdrant
    ports:
      - "6333:6333" # Dashboard: http://localhost:6333/dashboard
    volumes:
      - ./assets/qdrant_data:/qdrant/storage
  elasticsearch:
    build:
      dockerfile: elasticsearch.Dockerfile
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./assets/es_data:/usr/share/elasticsearch/data
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./assets/postgres_data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    restart: always
  jaeger:
    image: jaegertracing/all-in-one:1.72.0
    container_name: jaeger
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - LOG_LEVEL=debug
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "5778:5778"
      - "9411:9411"
    depends_on:
      - elasticsearch
    restart: unless-stopped
